const cloud = "https://beautyboothqa.sgp1.cdn.digitaloceanspaces.com/assets/mobile/";
export const menus = [
  {
    hasItems: false,
    isParent: true,
    isCategory: false,
    slug: "new",
    url: "new",
    name: "New",
    image:"new.png",
    items: [],
  },
  {
    hasItems: false,
    isParent: true,
    isCategory: false,
    slug: "brands",
    url:"brands",
    name: "BRANDS",
    image:"brand.png",
  },
  {
    hasItems: true,
    isParent: true,
    isCategory: true,
    slug: "skin-care",
    name: "Skin Care",
    url: "Skin-Care",
    image:"skin-care.png",
    items: [
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        name: "ampoule",
        url: "Skin-Care?sub=ampoule",
        slug: "ampoule",
        // image: "Serum.jpg",
        image: "skin-care/Ampoule.png",
        items: [],
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "bundle-set",
        // image: "Bundle.jpg",
        image: "skin-care/Bundle.png",
        items: [],
        name: "Bundle Set",
        url: "Skin-Care?sub=Bundle-Set",
      },
      {
        hasItems: true,
        isParent: false,
        isCategory: true,
        slug: "cleansers",
        // image: "Cleaner.jpg",
        image: "skin-care/Cleaner.png",
        items: [
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "cleansing-balms",
            url: "Skin-Care?sub=Cleansers&child=Cleansing-Balms",
            image: "cleansing_balm.jpg",
            items: [],
            name: "Cleansing Balms",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "cleansing-gels",
            image: "Gel.jpg",
            items: [],
            name: "Cleansing Gels",
            url: "Skin-Care?sub=Cleansers&child=Cleansing-Gels",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "cleansing-oils",
            image: "Oil.jpg",
            items: [],
            name: "Cleansing Oils",
            url: "Skin-Care?sub=Cleansers&child=Cleansing-Oils",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "cleansing-waters",
            image: "Water.jpg",
            items: [],
            name: "Cleansing Waters",
            url: "Skin-Care?sub=Cleansers&child=Cleansing-Waters",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "face-wipes",
            image: "face_wipes.jpg",
            items: [],
            name: "Face Wipes",
            url: "Skin-Care?sub=Cleansers&child=Face-Wipes",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "facial-cleansing-bars",
            image: "soap_bars.jpg",
            items: [],
            name: "Facial Cleansing bars",
            url: "Skin-Care?sub=Cleansers&child=Facial-Cleansing-bars",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "foaming-cleansers",
            image: "foam.jpg",
            items: [],
            name: "Foaming Cleansers",
            url: "Skin-Care?sub=Cleansers&child=Foaming-Cleansers",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "make-up-removers",
            image: "make_up_removal.jpg",
            items: [],
            name: "Make Up Removers",
            url: "Skin-Care?sub=Cleansers&child=Make-Up-Removers",
          },
        ],
        name: "Cleansers",
        url: "Skin-Care?sub=Cleansers",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "cream",
        // image: "Cream.jpg",
        image: "skin-care/Cream.png",
        items: [],
        name: "Cream",
        url: "Skin-Care?sub=Cream",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "essence",
        // image: "Essence.jpg",
        image: "skin-care/Essence.png",
        items: [],
        name: "Essence",
        url: "Skin-Care?sub=Essence",
      },
      {
        hasItems: true,
        isParent: false,
        isCategory: true,
        slug: "eye",
        name: "Eye",
        url: "Skin-Care?sub=Eye",
        // image: "Eye.jpg",
        image: "skin-care/Eye.png",
        items: [
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "eye-cream",
            image: "eye_cream.jpg",
            items: [],
            name: "Eye Cream",
            url: "Skin-Care?sub=Eye&child=Eye-Cream",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "eye-patch",
            image: "eye_patch.jpg",
            items: [],
            name: "Eye Patch",
            url: "Skin-Care?sub=Eye&child=Eye-Patch",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "eye-serum",
            image: "eye_cream.jpg",
            items: [],
            name: "Eye Serum",
            url: "Skin-Care?sub=Eye&child=Eye-Serum",
          },
        ],
        name: "Eye",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "face-roller",
        // image: "Roller.jpg",
        image: "skin-care/Roller.png",
        items: [],
        name: "Face Roller",
        url: "Skin-Care?sub=Face-Roller",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "kit",
        // image: "kIT.jpg",
        image: "skin-care/Kit.png",
        items: [],
        name: "Kit",
        url: "Skin-Care?sub=Kit",
      },
      {
        hasItems: true,
        isParent: false,
        isCategory: true,
        slug: "lip-care",
        // image: "Lipsticks.jpg",
        image: "skin-care/Lipsticks.png",
        items: [
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "lip-balm",
            image: null,
            items: [],
            name: "Lip Balm",
            url: "Skin-Care?sub=Lip-Care&child=Lip-Balm",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "lip-sleeping-mask",
            image: null,
            items: [],
            name: "Lip Sleeping Mask",
            url: "Skin-Care?sub=Lip-Care&child=Lip-Sleeping-Mask",
          },
        ],
        name: "Lip Care",
        url: "Skin-Care?sub=Lip-Care",
      },
      {
        hasItems: true,
        isParent: false,
        isCategory: true,
        slug: "masks-exfolators",
        // image: "Mask.jpg",
        image: "skin-care/Mask.png",
        items: [
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "exfoliators",
            image: "EXFOLATORS.jpg",
            items: [],
            name: "Exfoliators",
            url: "Skin-Care?sub=Masks-&-Exfolators&child=Exfoliators",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "mask-sheet",
            image: "mask_sheet.jpg",
            items: [],
            name: "Mask Sheet",
            url: "Skin-Care?sub=Masks-%26-Exfolators&child=Mask-Sheet",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "patchs",
            image: "Patchs.jpg",
            items: [],
            name: "Patchs",
            url: "Skin-Care?sub=Masks-%26-Exfolators&child=Patchs",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "wash-off-mask",
            image: "mask_off.jpg",
            items: [],
            name: "Wash Off Mask",
            url: "Skin-Care?sub=Masks-%26-Exfolators&child=Wash-Off-Mask",
          },
        ],
        name: "Masks & Exfolators",
        url: "Skin-Care?sub=Masks-%26-Exfolators",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "scrub",
        // image: "Scrub.jpg",
        image: "skin-care/Scrub.png",
        items: [],
        name: "Scrub",
        url: "Skin-Care?sub=Scrub",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "serum",
        // image: "Serum.jpg",
        image: "skin-care/Serum.png",
        items: [],
        name: "Serum",
        url: "Skin-Care?sub=Serum",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "soothing-gel",
        // image: "Soothing_gel.jpg",
        image: "skin-care/Soothing_gel.png",
        items: [],
        name: "Soothing Gel",
        url: "Skin-Care?sub=Soothing-Gel",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "sun-care",
        // image: "Sun_cream.jpg",
        image: "skin-care/Sun_cream.png",
        items: [],
        name: "Sun Care",
        url: "Skin-Care?sub=Sun-Care",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "toner",
        // image: "Toner.png",
        image: "skin-care/Toner.png",
        items: [],
        name: "Toner",
        url: "Skin-Care?sub=Toner",
      },
    ],
  },
  {
    hasItems: true,
    isParent: true,
    isCategory: true,
    slug: "body-care",
    name: "Body Care",
    url: "Body-Care",
    image:"body-care.png",
    items: [
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "bath",
        image: "body-care/bath.png",
        items: [],
        name: "Bath",
        url: "Body-Care?sub=Bath",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "bb-body-cream",
        image: "body-care/bb-body-cream.png",
        items: [],
        name: "BB Body Cream",
        url: "Body-Care?sub=BB-Body-Cream",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "body-sun-care",
        image: "body-care/body_sun.png",
        items: [],
        name: "Body Sun Care",
        url: "Body-Care?sub=Body-Sun-Care",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        image: "body-care/Cream.png",
        items: [],
        name: "Lotion",
        url: "Body-Care?sub=Lotion",
        slug: "lotion",
      },
      {
        hasItems: true,
        isParent: false,
        isCategory: true,
        slug: "hand-foot-care",
        image: "body-care/7.png",
        items: [
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "foot-mask",
            image: "foot.jpg",
            items: [],
            name: "Foot Mask",
            url: "Body-Care?sub=Hand-%26-Foot-Care&child=Foot-Mask",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "hand-cream",
            image: "9.jpg",
            items: [],
            name: "Hand Cream",
            url: "Body-Care?sub=Hand-%26-Foot-Care&child=Hand-Cream",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "hand-mask",
            image: "8.jpg",
            items: [],
            name: "Hand Mask",
            url: "Body-Care?sub=Hand-%26-Foot-Care&child=Hand-Mask",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "hand-sanitizer",
            image: "10.jpg",
            items: [],
            name: "Hand Sanitizer",
            url: "Body-Care?sub=Hand-%26-Foot-Care&child=Hand-Sanitizer",
          },
        ],
        name: "Hand & Foot Care",
        url: "Body-Care?sub=Hand-%26-Foot-Care",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "intimate-care",
        image: "body-care/intimate_care.png",
        items: [],
        name: "Intimate Care",
        url: "Body-Care?sub=Intimate-Care",
      },
      // {
      //   hasItems: false,
      //   isParent: false,
      //   isCategory: true,
      //   slug: "supplement",
      //   image: "Essence.jpg",
      //   items: [],
      //   name: "Supplement",
      //   url: "Body-Care?sub=Supplement",
      // },
    ],
  },
  {
    hasItems: true,
    isParent: true,
    isCategory: true,
    slug: "hair-care",
    name: "Hair Care",
    url: "Hair-Care",
    image:"hair-care.png",
    items: [
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "conditioner",
        image: "hair-care/Conditioner.png",
        items: [],
        name: "Conditioner",
        url: "Hair-Care?sub=Conditioner",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "hair-color",
        image: "hair-care/hair_color.png",
        items: [],
        name: "Hair Color",
        url: "Hair-Care?sub=Hair-Color",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "hair-cream-masks",
        image: "hair-care/hair_cream.png",
        items: [],
        name: "Hair Cream & Masks",
        url: "Hair-Care?sub=Hair-Cream-%26-Masks",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "hair-serum",
        image: "hair-care/hair_serum.png",
        items: [],
        name: "Hair Serum",
        url: "Hair-Care?sub=Hair-Serum",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "shampoo",
        image: "hair-care/shampoo.png",
        items: [],
        name: "Shampoo",
        url: "Hair-Care?sub=Shampoo",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "treatment",
        image: "hair-care/treatment.png",
        items: [],
        name: "Treatment",
        url: "Hair-Care?sub=Treatment",
      },
    ],
  },
  {
    hasItems: true,
    isParent: true,
    isCategory: true,
    slug: "makeup",
    name: "Makeup",
    url: "Makeup",
    image:"make-up.png",
    items: [
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "base-makeup",
        image: "make-up/base make up.png",
        items: [],
        name: "Base Makeup",
        url: "Makeup?sub=Base-Makeup",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "beauty-accessories",
        image: "make-up/accesso.png",
        items: [],
        name: "Beauty Accessories",
        url: "Makeup?sub=Beauty-Accessories",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        image: "make-up/base make up.png",
        items: [],
        name: "Blusher",
        url: "Makeup?sub=Blusher",
        slug: "blusher",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        slug: "cushion",
        image: "make-up/Cushion.png",
        items: [],
        name: "Cushion",
        url: "Makeup?sub=Cushion",
      },
      {
        hasItems: true,
        isParent: false,
        isCategory: true,
        slug: "eye",
        image: "make-up/Eyes.png",
        items: [
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "eye-liner",
            image: "Eye liner.jpg",
            items: [],
            name: "Eye Liner",
            url: "Makeup?sub=Eye&child=Eye-Liner",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "eye-shadow",
            image: "Eye shadow.jpg",
            items: [],
            name: "Eye Shadow",
            url: "Makeup?sub=Eye&child=Eye-Shadow",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "eyebrow",
            image: "eye brow.jpg",
            items: [],
            name: "EyeBrow",
            url: "Makeup?sub=Eye&child=EyeBrow",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "mascara",
            image: "mascara.jpg",
            items: [],
            name: "Mascara",
            url: "Makeup?sub=Eye&child=Mascara",
          },
        ],
        name: "Eye",
        url: "Makeup?sub=Eye",
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        image: "make-up/highlighter.png",
        items: [],
        name: "Highlighter",
        url: "Makeup?sub=Highlighter",
        slug: "highlighter",
      },
      {
        hasItems: true,
        isParent: false,
        isCategory: true,
        slug: "lip",
        image: "make-up/Lip.png",
        items: [
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "lip-tint",
            image: "Lip tint.jpg",
            items: [],
            name: "Lip Tint",
            url: "Makeup?sub=Lip&child=Lip-Tint",
          },
          {
            hasItems: false,
            isParent: false,
            isCategory: true,
            slug: "lipstick",
            image: "lipstick.jpg",
            items: [],
            name: "lipstick",
            url: "Makeup?sub=Lip&child=lipstick",
          },
        ],
        name: "Lip",
        url: "Makeup?sub=Lip",
      },
    ],
  },
  {
    hasItems: false,
    isParent: true,
    isCategory: true,
    slug: "fragrance",
    name: "Fragrance",
    url: "Fragrance",
    image:"fragrance.png",
    items: [],
  },
  {
    hasItems: true,
    isParent: true,
    isCategory: true,
    slug: "accessories",
    name: "Accessories",
    url: "Accessories",
    image:"accessories.png",
    items: [
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        name: "Beauty Tools",
        url: "Accessories?sub=Beauty-Tools",
        slug: "beauty-tools",
        items: [],
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        name: "Women's Fashion Jewelry",
        url: "Accessories?sub=Women's-Fashion-Jewelry",
        slug: "womens-fashion-jewelry-accessories",
        items: [],
      },
      {
        hasItems: false,
        isParent: false,
        isCategory: true,
        name: "Candles",
        url: "Accessories?sub=Candles",
        slug: "candles",
        items: [],
      },
    ],
  },
  {
    hasItems: false,
    isParent: true,
    isCategory: false,
    slug: "campaigns",
    name: "Campaigns",
    url: "campaigns",
    image:"campaign.png",
    items: [],
  },
  {
    hasItems: false,
    isParent: true,
    isCategory: false,
    slug: "best-selling",
    url: "best-selling",
    name: "Best Selling",
    image:"best-selling.png",
    items: [],
  },
];