export const GET_LAYOUT_DATA = "GET_LAYOUT_DATA";
export const GET_MOBILE_BANNER = "GET_MOBILE_BANNER";
export const MENU_LOADED = "MENU_LOADED";
export const GET_HOME_PAGE_DATA = "GET_HOME_PAGE_DATA";
export const BEST_SELLING_PRODUCTS = "BEST_SELLING_PRODUCTS";
// export const TRENDING_ATTRIBUTES = "TRENDING_ATTRIBUTES";
// export const NEW_ARRIVALS = "NEW_ARRIVALS";
// export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
// export const GET_BEST_BRANDS = "GET_BEST_BRANDS";
// export const ADD_TO_CART = "ADD_TO_CART";
// export const GET_CART_ITEMS = "GET_CART_ITEMS";
// export const SET_CART_FROM_LOCAL = "SET_CART_FROM_LOCAL";
// export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
// export const PLUS_ONE_TO_CART = "PLUS_ONE_TO_CART";
// export const MINUS_ONE_TO_CART = "MINUS_ONE_TO_CART";
// export const INPUT_ITEM_TO_CART = "INPUT_ITEM_TO_CART";
// export const EMPTY_CART = "EMPTY_CART";
// export const GET_ATTRIBUTE_DETAILS = "GET_ATTRIBUTE_DETAILS";
// export const SET_CART_AFTER_PRICE_CHANGE = "SET_CART_AFTER_PRICE_CHANGE";

// //auth actions

// export const LOGIN_USER = "LOGIN_USER";
// export const SET_CURRENT_USER = "SET_CURRENT_USER";
